export const IPPIndustyMapping = {
  cheBienGo : `N'Chế biến gỗ và sản xuất sản phẩm từ gỗ, tre, nứa (trừ giường, tủ, bàn ghế); sản xuất sản phẩm từ rơm, rạ và vật liệu tết bện'`,
  cheBienKhac : `N'Công nghiệp chế biến, chế tạo khác'`,
  det : `N'Dệt'`,
  inSaoChep : `N'In, sao chép bản ghi các loại'`,
  Da : `N'Sản xuất da và các sản phẩm có liên quan'`,
  doUong : `N'Sản xuất đồ uống'`,
  giay : `N'Sản xuất giấy và sản phẩm từ giấy'`,
  giuongTu : `N'Sản xuất giường, tủ, bàn, ghế'`,
  hoaChat : `N'Sản xuất hoá chất và sản phẩm hoá chất'`,
  kimLoai : `N'Sản xuất kim loại'`,
  mayMoc : `N'Sản xuất máy móc, thiết bị chưa được phân vào đâu'`,
  vanTai : `N'Sản xuất phương tiện vận tải khác'`,
  dienTu : `N'Sản xuất sản phẩm điện tử, máy vi tính và sản phẩm quang học'`,
  thuocLa : `N'Sản xuất sản phẩm thuốc lá'`,
  caoSu : `N'Sản xuất sản phẩm từ cao su và plastic'`,
  phiKimLoai : `N'Sản xuất sản phẩm từ khoáng phi kim loại khác'`,
  kimLoaiDucSan : `N'Sản xuất sản phẩm từ kim loại đúc sẵn (trừ máy móc, thiết bị)'`,
  than : `N'Sản xuất than cốc, sản phẩm dầu mỏ tinh chế'`,
  dien : `N'Sản xuất thiết bị điện'`,
  duocLieu : `N'Sản xuất thuốc, hoá dược và dược liệu'`,
  trangPhuc : `N'Sản xuất trang phục'`,
  dongCo : `N'Sản xuất xe có động cơ, rơ moóc'`,
  thucPham : `N'Sản xuất, chế biến thực phẩm'`,
  all : `N'TOÀN NGÀNH CHẾ BIẾN, CHẾ TẠO'`,
}

export const IPPIndusProductionIndexMapping = {
  cheBienGo: `N'Chế biến gỗ và sản xuất sản phẩm từ gỗ, tre, nứa (trừ giường, tủ, bàn ghế); sản xuất sản phẩm từ rơm, rạ và vật liệu tết bện'`,
  cheTao: `N'Công nghiệp chế biến, chế tạo'`,
  cheBienKhac: `N'Công nghiệp chế biến, chế tạo khác'`,
  cungCapNuoc: `N'Cung cấp nước; hoạt động quản lý và xử lý rác thải, nước thải'`,
  det: `N'Dệt'`,
  moQuang: `N'Hoạt động dịch vụ hỗ trợ khai thác mỏ và quặng'`,
  rac: `N'Hoạt động thu gom, xử lý và tiêu huỷ rác thải; tái chế phế liệu'`,
  inSaoChep: `N'In, sao chép bản ghi các loại'`,
  khaiKhoang: `N'Khai khoáng'`,
  khaiKhoangKhac: `N'Khai khoáng khác'`,
  dauTho: `N'Khai thác dầu thô và khí đốt tự nhiên'`,
  quangKimLoai: `N'Khai thác quặng kim loại'`,
  than: `N'Khai thác than cứng và than non'`,
  khaiThacNuoc: `N'Khai thác, xử lý và cung cấp nước'`,
  Da: `N'Sản xuất da và các sản phẩm có liên quan'`,
  doUong: `N'Sản xuất đồ uống'`,
  giay: `N'Sản xuất giấy và sản phẩm từ giấy'`,
  giuongTu: `N'Sản xuất giường, tủ, bàn, ghế'`,
  hoaChat: `N'Sản xuất hoá chất và sản phẩm hoá chất'`,
  kimLoai: `N'Sản xuất kim loại'`,
  mayMoc: `N'Sản xuất máy móc, thiết bị chưa được phân vào đâu'`,
  vanTai: `N'Sản xuất phương tiện vận tải khác'`,
  dienTu: `N'Sản xuất sản phẩm điện tử, máy vi tính và sản phẩm quang học'`,
  thuocLa: `N'Sản xuất sản phẩm thuốc lá'`,
  caoSu: `N'Sản xuất sản phẩm từ cao su và plastic'`,
  phiKimLoai: `N'Sản xuất sản phẩm từ khoáng phi kim loại khác'`,
  phiKimLoaiDucSan: `N'Sản xuất sản phẩm từ kim loại đúc sẵn (trừ máy móc, thiết bị)'`,
  thanCoc: `N'Sản xuất than cốc, sản phẩm dầu mỏ tinh chế'`,
  dien: `N'Sản xuất thiết bị điện'`,
  duocLieu: `N'Sản xuất thuốc, hoá dược và dược liệu'`,
  tranhPhuc: `N'Sản xuất trang phục'`,
  dieuHoa: `N'Sản xuất và phân phối điện, khí đốt, nước nóng, hơi nước và điều hoà không khí'`,
  roMooc: `N'Sản xuất xe có động cơ, rơ moóc'`,
  thucPham: `N'Sản xuất, chế biến thực phẩm'`,
  baoDuong: `N'Sửa chữa, bảo dưỡng và lắp đặt máy móc, thiết bị'`,
};