export const IPPIndustyMapping = {
  cheBienGo : `N'Chế biến gỗ và sản xuất sản phẩm từ gỗ, tre, nứa (trừ giường, tủ, bàn ghế); sản xuất sản phẩm từ rơm, rạ và vật liệu tết bện'`,
  cheBienKhac : `N'Công nghiệp chế biến, chế tạo khác'`,
  det : `N'Dệt'`,
  inSaoChep : `N'In, sao chép bản ghi các loại'`,
  Da : `N'Sản xuất da và các sản phẩm có liên quan'`,
  doUong : `N'Sản xuất đồ uống'`,
  giay : `N'Sản xuất giấy và sản phẩm từ giấy'`,
  giuongTu : `N'Sản xuất giường, tủ, bàn, ghế'`,
  hoaChat : `N'Sản xuất hoá chất và sản phẩm hoá chất'`,
  kimLoai : `N'Sản xuất kim loại'`,
  mayMoc : `N'Sản xuất máy móc, thiết bị chưa được phân vào đâu'`,
  vanTai : `N'Sản xuất phương tiện vận tải khác'`,
  dienTu : `N'Sản xuất sản phẩm điện tử, máy vi tính và sản phẩm quang học'`,
  thuocLa : `N'Sản xuất sản phẩm thuốc lá'`,
  caoSu : `N'Sản xuất sản phẩm từ cao su và plastic'`,
  phiKimLoai : `N'Sản xuất sản phẩm từ khoáng phi kim loại khác'`,
  kimLoaiDucSan : `N'Sản xuất sản phẩm từ kim loại đúc sẵn (trừ máy móc, thiết bị)'`,
  than : `N'Sản xuất than cốc, sản phẩm dầu mỏ tinh chế'`,
  dien : `N'Sản xuất thiết bị điện'`,
  duocLieu : `N'Sản xuất thuốc, hoá dược và dược liệu'`,
  trangPhuc : `N'Sản xuất trang phục'`,
  dongCo : `N'Sản xuất xe có động cơ, rơ moóc'`,
  thucPham : `N'Sản xuất, chế biến thực phẩm'`,
  all : `N'TOÀN NGÀNH CHẾ BIẾN, CHẾ TẠO'`,
}

export const IPPIndusProductionIndexMapping = {
  cheBienGo: `N'Chế biến gỗ và sản xuất sản phẩm từ gỗ, tre, nứa (trừ giường, tủ, bàn ghế); sản xuất sản phẩm từ rơm, rạ và vật liệu tết bện'`,
  cheTao: `N'Công nghiệp chế biến, chế tạo'`,
  cheBienKhac: `N'Công nghiệp chế biến, chế tạo khác'`,
  cungCapNuoc: `N'Cung cấp nước; hoạt động quản lý và xử lý rác thải, nước thải'`,
  det: `N'Dệt'`,
  moQuang: `N'Hoạt động dịch vụ hỗ trợ khai thác mỏ và quặng'`,
  rac: `N'Hoạt động thu gom, xử lý và tiêu huỷ rác thải; tái chế phế liệu'`,
  inSaoChep: `N'In, sao chép bản ghi các loại'`,
  khaiKhoang: `N'Khai khoáng'`,
  khaiKhoangKhac: `N'Khai khoáng khác'`,
  dauTho: `N'Khai thác dầu thô và khí đốt tự nhiên'`,
  quangKimLoai: `N'Khai thác quặng kim loại'`,
  than: `N'Khai thác than cứng và than non'`,
  khaiThacNuoc: `N'Khai thác, xử lý và cung cấp nước'`,
  Da: `N'Sản xuất da và các sản phẩm có liên quan'`,
  doUong: `N'Sản xuất đồ uống'`,
  giay: `N'Sản xuất giấy và sản phẩm từ giấy'`,
  giuongTu: `N'Sản xuất giường, tủ, bàn, ghế'`,
  hoaChat: `N'Sản xuất hoá chất và sản phẩm hoá chất'`,
  kimLoai: `N'Sản xuất kim loại'`,
  mayMoc: `N'Sản xuất máy móc, thiết bị chưa được phân vào đâu'`,
  vanTai: `N'Sản xuất phương tiện vận tải khác'`,
  dienTu: `N'Sản xuất sản phẩm điện tử, máy vi tính và sản phẩm quang học'`,
  thuocLa: `N'Sản xuất sản phẩm thuốc lá'`,
  caoSu: `N'Sản xuất sản phẩm từ cao su và plastic'`,
  phiKimLoai: `N'Sản xuất sản phẩm từ khoáng phi kim loại khác'`,
  phiKimLoaiDucSan: `N'Sản xuất sản phẩm từ kim loại đúc sẵn (trừ máy móc, thiết bị)'`,
  thanCoc: `N'Sản xuất than cốc, sản phẩm dầu mỏ tinh chế'`,
  dien: `N'Sản xuất thiết bị điện'`,
  duocLieu: `N'Sản xuất thuốc, hoá dược và dược liệu'`,
  tranhPhuc: `N'Sản xuất trang phục'`,
  dieuHoa: `N'Sản xuất và phân phối điện, khí đốt, nước nóng, hơi nước và điều hoà không khí'`,
  roMooc: `N'Sản xuất xe có động cơ, rơ moóc'`,
  thucPham: `N'Sản xuất, chế biến thực phẩm'`,
  baoDuong: `N'Sửa chữa, bảo dưỡng và lắp đặt máy móc, thiết bị'`,
};

export const IPPMostIndustryProductionMapping = {
  acQuyDienCacLoai: `N'Ắc quy điện các loại (Nghìn kwh)'`,
  baoBiVaTuiBangPlastic: `N'Bao bì và túi bằng plastic (Nghìn tấn)'`,
  baoInVaCacSanPhamInKhac: `N'Báo in và các sản phẩm in khác (Tỷ trang)'`,
  biaCacLoai: `N'Bia các loại (Triệu lít)'`,
  bongDenDien: `N'Bóng đèn điện (Triệu cái)'`,
  botGiatVaCacChePhamDungDeTayRua: `N'Bột giặt và các chế phẩm dùng để tẩy, rửa (Nghìn tấn)'`,
  botNgot: `N'Bột ngọt (Nghìn tấn)'`,
  caPheBotVaCaPheHoaTan: `N'Cà phê bột và cà phê hòa tan (Nghìn tấn)'`,
  catCacLoai: `N'Cát các loại* (Nghìn m3)'`,
  cheCheBien: `N'Chè chế biến (Nghìn tấn)'`,
  daKhaiThac: `N'Đá khai thác (Nghìn m3)'`,
  dauGoiDauXa: `N'Dầu gội, dầu xả (Tấn)'`,
  dauThoKhaiThac: `N'Dầu thô khai thác (Nghìn tấn)'`,
  dauThoKhaiThacTrongNuoc: `N'Dầu thô khai thác trong nước (Nghìn tấn)'`,
  dauThucVatTinhLuyen: `N'Dầu thực vật tinh luyện (Nghìn tấn)'`,
  dienPhatRa: `N'Điện phát ra (Triệu Kwh)'`,
  dienThoaiCoDinh: `N'Điện thoại cố định (Nghìn cái)'`,
  dienThoaiDiDong: `N'Điện thoại di động (Triệu cái)'`,
  duongKinh: `N'Đường kính (Nghìn tấn)'`,
  gachNung: `N'Gạch nung (Triệu viên)'`,
  gaoXayXat: `N'Gạo xay xát (Nghìn tấn)'`,
  giayThethao: `N'Giày thể thao (Triệu đôi)'`,
  giayVai: `N'Giày vải (Triệu đôi)'`,
  giayBia: `N'Giấy, bìa (Nghìn tấn)'`,
  giayDepDa: `N'Giày, dép da (Triệu đôi)'`,
  goXe: `N'Gỗ xẻ (Nghìn m3)'`,
  khiTuNhienODangKhi: `N'Khí tự nhiên ở dạng khí (Triệu m3 )'`,
  lopOtoMayKeoLoaiBomHoi: `N'Lốp ô tô, máy kéo loại bơm hơi (Nghìn cái)'`,
  lopXeMayXeDapLoaiBomHoi: ` N'Lốp xe máy, xe đạp loại bơm hơi (Nghìn cái)'`,
  mayAnhKyThuatSo: `N'Máy ảnh kỹ thuật số (Nghìn cái)'`,
  mayDieuHoaKhongKhi: `N'Máy điều hoà không khí (Nghìn cái)'`,
  mayGiatDungTrongGiaDinh: `N'Máy giặt dùng trong gia đình (Nghìn cái)'`,
  mayInCacLoai: `N'Máy in các loại (Nghìn cái)'`,
  mayTuotLua: `N'Máy tuốt lúa (Nghìn cái)'`,
  muoiBien: `N'Muối biển (Nghìn tấn)'`,
  ngoiNung: `N'Ngói nung (Triệu viên)'`,
  nuocKhoang: `N'Nước khoáng (Triệu lít)'`,
  nuocMam: `N'Nước mắm (Triệu lít)'`,
  nuocMayThuongPham: `N'Nước máy thương phẩm (Triệu m3)'`,
  nuocTinhKhiet: `N'Nước tinh khiết (Triệu lít)'`,
  otoLapRap: `N'Ô tô lắp ráp (Nghìn cái)'`,
  phanHoaHoc: `N'Phân hóa học (Nghìn tấn)'`,
  phanNPK: `N'Phân NPK (Nghìn tấn)'`,
  photPhoVang: `N'Phốt pho vàng (Tấn)'`,
  pinQuyChuan15V: `N'Pin quy chuẩn (1,5V) (Triệu viên)'`,
  quaVaHatDongHop: `N'Quả và hạt đóng hộp (Nghìn tấn)'`,
  quanAoMacThuong: `N'Quần áo mặc thường (Triệu cái)'`,
  quangAntimoanVaTinhQuangAntimoan: `N'Quặng antimoan và tinh quặng antimoan (Tấn)'`,
  quangApatit: `N'Quặng apatít (Nghìn tấn)'`,
  quangDongVaTinhQuangDong: `N'Quặng đồng và tinh quặng đồng (Tấn)'`,
  quangSatVaTinhQuangSat: `N'Quặng sắt và tinh quặng sắt (Nghìn tấn)'`,
  quangTitanVaTinhQuangTitan: `N'Quặng Titan và tinh quàng Titan (Nghìn tấn)'`,
  quatDienDungTrongGiaDinh: `N'Quạt điện dùng trong gia đình (Nghìn cái)'`,
  rauDongHop: `N'Rau đóng hộp* (Tấn)'`,
  ruouManhVaRuouTrang: `N'Rượu mạnh và rượu trắng (Triệu lít)'`,
  samDungChoOtoMayBay: `N'Săm dùng cho ô tô, máy bay (Nghìn cái)'`,
  samDungChoXeDapXeMay: `N'Săm dùng cho xe đạp, xe máy (Nghìn cái)'`,
  satThepDangThoiDucHoacDangThoKhac:
    `N'Sắt, thép dạng thỏi đúc hoặc dạng thô khác (Nghìn tấn)'`,
  soi: `N'Sợi (Nghìn tấn)'`,
  soiDaCuoi: `N'Sỏi, đá cuội (Nghìn m3)'`,
  suDanDung: `N'Sứ dân dụng (Triệu cái)'`,
  suVeSinh: `N'Sứ vệ sinh (Nghìn cái)'`,
  suaBot: `N'Sữa bột (Nghìn tấn)'`,
  suaTamSuaRuaMat: `N'Sữa tắm, sữa rửa mặt (Tấn)'`,
  suaTuoi: `N'Sữa tươi (Triệu lít)'`,
  tamLopFiproXiMang: `N'Tấm lợp fipro xi-măng (Triệu m2)'`,
  thanSach: `N'Than sạch (Nghìn tấn)'`,
  thepCanVaThepHinh: `N'Thép cán và thép hình (Nghìn tấn)'`,
  thitHop: `N'Thịt hộp (Tấn)'`,
  thucAnChoGiaSucVaGiaCam: `N'Thức ăn cho gia súc và gia cầm (Nghìn tấn)'`,
  thucAnChoThuySan: `N'Thức ăn cho thủy sản (Nghìn tấn)'`,
  thuocDanhRang: `N'Thuốc đánh răng (Tấn)'`,
  thuocDietCo: `N'Thuốc diệt cỏ (Tấn)'`,
  thuocLa: `N'Thuốc lá (Triệu bao)'`,
  thuocTruSau: `N'Thuốc trừ sâu (Tấn)'`,
  thuySanDongHop: `N'Thủy sản đóng hộp (Tấn)'`,
  thuySanUopDong: `N'Thủy sản ướp đông (Nghìn tấn)'`,
  tiViLapRap: `N'Ti vi lắp ráp (Nghìn cái)'`,
  tuLanhVaTuDongDungTrongGiaDinh:
    `N'Tủ lạnh và tủ đông dùng trong gia đình (Nghìn cái)'`,
  vai: `N'Vải (Triệum2)'`,
  xeDapCacLoai: `N'Xe đạp các loại (Nghìn cái)'`,
  xeMoToXeMayLapRap: `N'Xe mô tô, xe máy lắp ráp (Nghìn cái)'`,
  xiMang: `N'Xi măng (Nghìn tấn)'`,
};