export const IPPIndustyMapping = {
  cheBienGo : `N'Chế biến gỗ và sản xuất sản phẩm từ gỗ, tre, nứa (trừ giường, tủ, bàn ghế); sản xuất sản phẩm từ rơm, rạ và vật liệu tết bện'`,
  cheBienKhac : `N'Công nghiệp chế biến, chế tạo khác'`,
  det : `N'Dệt'`,
  inSaoChep : `N'In, sao chép bản ghi các loại'`,
  Da : `N'Sản xuất da và các sản phẩm có liên quan'`,
  doUong : `N'Sản xuất đồ uống'`,
  giay : `N'Sản xuất giấy và sản phẩm từ giấy'`,
  giuongTu : `N'Sản xuất giường, tủ, bàn, ghế'`,
  hoaChat : `N'Sản xuất hoá chất và sản phẩm hoá chất'`,
  kimLoai : `N'Sản xuất kim loại'`,
  mayMoc : `N'Sản xuất máy móc, thiết bị chưa được phân vào đâu'`,
  vanTai : `N'Sản xuất phương tiện vận tải khác'`,
  dienTu : `N'Sản xuất sản phẩm điện tử, máy vi tính và sản phẩm quang học'`,
  thuocLa : `N'Sản xuất sản phẩm thuốc lá'`,
  caoSu : `N'Sản xuất sản phẩm từ cao su và plastic'`,
  phiKimLoai : `N'Sản xuất sản phẩm từ khoáng phi kim loại khác'`,
  kimLoaiDucSan : `N'Sản xuất sản phẩm từ kim loại đúc sẵn (trừ máy móc, thiết bị)'`,
  than : `N'Sản xuất than cốc, sản phẩm dầu mỏ tinh chế'`,
  dien : `N'Sản xuất thiết bị điện'`,
  duocLieu : `N'Sản xuất thuốc, hoá dược và dược liệu'`,
  trangPhuc : `N'Sản xuất trang phục'`,
  dongCo : `N'Sản xuất xe có động cơ, rơ moóc'`,
  thucPham : `N'Sản xuất, chế biến thực phẩm'`,
  all : `N'TOÀN NGÀNH CHẾ BIẾN, CHẾ TẠO'`,
}