export enum RedisKeys {
  Industry = 'industry',
  MarketVolatility = 'market-volatility',
  NetTransactionValue = 'net-transaction-value',
  MarketLiquidity = 'market-liquidity',
  ExchangeVolume = 'exchange-volume',
  StockNews = 'stock-news',
  StockEvents = 'stock-events',
  DomesticIndex = 'domestic-index',
  InternationalIndex = 'international-index',
  TopNetForeign = 'top-net-foreign',
  TopNetForeignByEx = 'top-net-foreign-by-ex',
  NetForeign = 'net-foreign',
  TopRoc5 = 'top-roc-5',
  MerchandisePrice = 'merchandise-price',
  User = 'user',
  HNXTicker = 'hnx-ticker',
  HSXTicker = 'hsx-ticker',
  UPCOMTicker = 'upcom-ticker',
  Rsi = 'rsi',
  MarketEvaluation = 'market-evaluation',
  VnIndex = 'vn-index'
}
