export enum RedisKeys {
  Industry = 'industry',
  MarketVolatility = 'market-volatility',
  MarketBreadth = 'market-breadth',
  NetTransactionValue = 'net-transaction-value',
  MarketLiquidity = 'market-liquidity',
  ExchangeVolume = 'exchange-volume',
  StockNews = 'stock-news',
  StockMacroNews = 'stock-macro-news',
  StockEvents = 'stock-events',
  DomesticIndex = 'domestic-index',
  InternationalIndex = 'international-index',
  TopNetForeign = 'top-net-foreign',
  TopNetForeignByEx = 'top-net-foreign-by-ex',
  NetForeign = 'net-foreign',
  TopRoc5 = 'top-roc-5',
  MerchandisePrice = 'merchandise-price',
  User = 'user',
  HNX = 'hnx-ticker',
  HOSE = 'hsx-ticker',
  UPCoM = 'upcom-ticker',
  Rsi = 'rsi',
  MarketEvaluation = 'market-evaluation',
  LineChart = 'line-chart',
  IndustryFull = 'industry-full',
  MarketMap = 'market-map',
  LiquidityContribute = 'liquidity-contribute',
  TickerContribute = 'ticker-contribute',
  TickerIndustry = 'ticker-industry',
  TickerPrice = 'ticker-price',

  InvestorTransaction = 'investor-transaction',
  CashFlowValue = 'cash-flow-value',

  BienDongThiTruong = 'bien-dong-thi-truong',
  KLCPLH = 'klcplh',
  MarketCap = 'market-cap',

  InvestorTransactionRatio = 'investor-transaction-ratio',
  InvestorTransactionCashFlowRatio = 'investor-transaction-cash-flow-ratio',

  TopNetBuyIndustry = 'top-net-buy-industry',
}
