import { ApiProperty } from "@nestjs/swagger";


export class IPPIndustryDto {
    @ApiProperty({
        type: String,
        description: `
        cheBienGo : 'Chế biến gỗ và sản xuất sản phẩm từ gỗ, tre, nứa (trừ giường, tủ, bàn ghế); sản xuất sản phẩm từ rơm, rạ và vật liệu tết bện',
        cheBienKhac : 'Công nghiệp chế biến, chế tạo khác',
        det : 'Dệt',
        inSaoChep : 'In, sao chép bản ghi các loại',
        Da : 'Sản xuất da và các sản phẩm có liên quan',
        doUong : 'Sản xuất đồ uống',
        giay : 'Sản xuất giấy và sản phẩm từ giấy',
        giuongTu : 'Sản xuất giường, tủ, bàn, ghế',
        hoaChat : 'Sản xuất hoá chất và sản phẩm hoá chất',
        kimLoai : 'Sản xuất kim loại',
        mayMoc : 'Sản xuất máy móc, thiết bị chưa được phân vào đâu',
        vanTai : 'Sản xuất phương tiện vận tải khác',
        dienTu : 'Sản xuất sản phẩm điện tử, máy vi tính và sản phẩm quang học',
        thuocLa : 'Sản xuất sản phẩm thuốc lá',
        caoSu : 'Sản xuất sản phẩm từ cao su và plastic',
        phiKimLoai : 'Sản xuất sản phẩm từ khoáng phi kim loại khác',
        kimLoaiDucSan : 'Sản xuất sản phẩm từ kim loại đúc sẵn (trừ máy móc, thiết bị)',
        than : 'Sản xuất than cốc, sản phẩm dầu mỏ tinh chế',
        dien : 'Sản xuất thiết bị điện',
        duocLieu : 'Sản xuất thuốc, hoá dược và dược liệu',
        trangPhuc : 'Sản xuất trang phục',
        dongCo : 'Sản xuất xe có động cơ, rơ moóc',
        thucPham : 'Sản xuất, chế biến thực phẩm',
        all : 'TOÀN NGÀNH CHẾ BIẾN, CHẾ TẠO',
    `
    })
    industry: string;
}

export class IPPProductionIndexDto {
  @ApiProperty({
    type: String,
    description: `
        cheBienGo: 'Chế biến gỗ và sản xuất sản phẩm từ gỗ, tre, nứa (trừ giường, tủ, bàn ghế); sản xuất sản phẩm từ rơm, rạ và vật liệu tết bện',
        cheTao: 'Công nghiệp chế biến, chế tạo',
        cheBienKhac: 'Công nghiệp chế biến, chế tạo khác',
        cungCapNuoc: 'Cung cấp nước; hoạt động quản lý và xử lý rác thải, nước thải',
        det: 'Dệt',
        moQuang: 'Hoạt động dịch vụ hỗ trợ khai thác mỏ và quặng',
        rac: 'Hoạt động thu gom, xử lý và tiêu huỷ rác thải; tái chế phế liệu',
        inSaoChep: 'In, sao chép bản ghi các loại',
        khaiKhoang: 'Khai khoáng',
        khaiKhoangKhac: 'Khai khoáng khác',
        dauTho: 'Khai thác dầu thô và khí đốt tự nhiên',
        quangKimLoai: 'Khai thác quặng kim loại',
        than: 'Khai thác than cứng và than non',
        khaiThacNuoc: 'Khai thác, xử lý và cung cấp nước',
        Da: 'Sản xuất da và các sản phẩm có liên quan',
        doUong: 'Sản xuất đồ uống',
        giay: 'Sản xuất giấy và sản phẩm từ giấy',
        giuongTu: 'Sản xuất giường, tủ, bàn, ghế',
        hoaChat: 'Sản xuất hoá chất và sản phẩm hoá chất',
        kimLoai: 'Sản xuất kim loại',
        mayMoc: 'Sản xuất máy móc, thiết bị chưa được phân vào đâu',
        vanTai: 'Sản xuất phương tiện vận tải khác',
        dienTu: 'Sản xuất sản phẩm điện tử, máy vi tính và sản phẩm quang học',
        thuocLa: 'Sản xuất sản phẩm thuốc lá',
        caoSu: 'Sản xuất sản phẩm từ cao su và plastic',
        phiKimLoai: 'Sản xuất sản phẩm từ khoáng phi kim loại khác',
        phiKimLoaiDucSan: 'Sản xuất sản phẩm từ kim loại đúc sẵn (trừ máy móc, thiết bị)',
        thanCoc: 'Sản xuất than cốc, sản phẩm dầu mỏ tinh chế',
        dien: 'Sản xuất thiết bị điện',
        duocLieu: 'Sản xuất thuốc, hoá dược và dược liệu',
        tranhPhuc: 'Sản xuất trang phục',
        dieuHoa: 'Sản xuất và phân phối điện, khí đốt, nước nóng, hơi nước và điều hoà không khí',
        roMooc: 'Sản xuất xe có động cơ, rơ moóc',
        thucPham: 'Sản xuất, chế biến thực phẩm',
        baoDuong: 'Sửa chữa, bảo dưỡng và lắp đặt máy móc, thiết bị',
    `,
  })
  industry: string;
}

export class IPPMostIndusProductionDto {
  @ApiProperty({
    type: String,
    description: `
        acQuyDienCacLoai: 'Ắc quy điện các loại (Nghìn kwh)',
        baoBiVaTuiBangPlastic: 'Bao bì và túi bằng plastic (Nghìn tấn)',
        baoInVaCacSanPhamInKhac: 'Báo in và các sản phẩm in khác (Tỷ trang)',
        biaCacLoai: 'Bia các loại (Triệu lít)',
        bongDenDien: 'Bóng đèn điện (Triệu cái)',
        botGiatVaCacChePhamDungDeTayRua: 'Bột giặt và các chế phẩm dùng để tẩy, rửa (Nghìn tấn)',
        botNgot: 'Bột ngọt (Nghìn tấn)',
        caPheBotVaCaPheHoaTan: 'Cà phê bột và cà phê hòa tan (Nghìn tấn)',
        catCacLoai: 'Cát các loại* (Nghìn m3)',
        cheCheBien: 'Chè chế biến (Nghìn tấn)',
        daKhaiThac: 'Đá khai thác (Nghìn m3)',
        dauGoiDauXa: 'Dầu gội, dầu xả (Tấn)',
        dauThoKhaiThac: 'Dầu thô khai thác (Nghìn tấn)',
        dauThoKhaiThacTrongNuoc: 'Dầu thô khai thác trong nước (Nghìn tấn)',
        dauThucVatTinhLuyen: 'Dầu thực vật tinh luyện (Nghìn tấn)',
        dienPhatRa: 'Điện phát ra (Triệu Kwh)',
        dienThoaiCoDinh: 'Điện thoại cố định (Nghìn cái)',
        dienThoaiDiDong: 'Điện thoại di động (Triệu cái)',
        duongKinh: 'Đường kính (Nghìn tấn)',
        gachNung: 'Gạch nung (Triệu viên)',
        gaoXayXat: 'Gạo xay xát (Nghìn tấn)',
        giayThethao: 'Giày thể thao (Triệu đôi)',
        giayVai: 'Giày vải (Triệu đôi)',
        giayBia: 'Giấy, bìa (Nghìn tấn)',
        giayDepDa: 'Giày, dép da (Triệu đôi)',
        goXe: 'Gỗ xẻ (Nghìn m3)',
        khiTuNhienODangKhi: 'Khí tự nhiên ở dạng khí (Triệu m3 )',
        lopOtoMayKeoLoaiBomHoi: 'Lốp ô tô, máy kéo loại bơm hơi (Nghìn cái)',
        lopXeMayXeDapLoaiBomHoi:  N'Lốp xe máy, xe đạp loại bơm hơi (Nghìn cái)',
        mayAnhKyThuatSo: 'Máy ảnh kỹ thuật số (Nghìn cái)',
        mayDieuHoaKhongKhi: 'Máy điều hoà không khí (Nghìn cái)',
        mayGiatDungTrongGiaDinh: 'Máy giặt dùng trong gia đình (Nghìn cái)',
        mayInCacLoai: 'Máy in các loại (Nghìn cái)',
        mayTuotLua: 'Máy tuốt lúa (Nghìn cái)',
        muoiBien: 'Muối biển (Nghìn tấn)',
        ngoiNung: 'Ngói nung (Triệu viên)',
        nuocKhoang: 'Nước khoáng (Triệu lít)',
        nuocMam: 'Nước mắm (Triệu lít)',
        nuocMayThuongPham: 'Nước máy thương phẩm (Triệu m3)',
        nuocTinhKhiet: 'Nước tinh khiết (Triệu lít)',
        otoLapRap: 'Ô tô lắp ráp (Nghìn cái)',
        phanHoaHoc: 'Phân hóa học (Nghìn tấn)',
        phanNPK: 'Phân NPK (Nghìn tấn)',
        photPhoVang: 'Phốt pho vàng (Tấn)',
        pinQuyChuan15V: 'Pin quy chuẩn (1,5V) (Triệu viên)',
        quaVaHatDongHop: 'Quả và hạt đóng hộp (Nghìn tấn)',
        quanAoMacThuong: 'Quần áo mặc thường (Triệu cái)',
        quangAntimoanVaTinhQuangAntimoan: 'Quặng antimoan và tinh quặng antimoan (Tấn)',
        quangApatit: 'Quặng apatít (Nghìn tấn)',
        quangDongVaTinhQuangDong: 'Quặng đồng và tinh quặng đồng (Tấn)',
        quangSatVaTinhQuangSat: 'Quặng sắt và tinh quặng sắt (Nghìn tấn)',
        quangTitanVaTinhQuangTitan: 'Quặng Titan và tinh quàng Titan (Nghìn tấn)',
        quatDienDungTrongGiaDinh: 'Quạt điện dùng trong gia đình (Nghìn cái)',
        rauDongHop: 'Rau đóng hộp* (Tấn)',
        ruouManhVaRuouTrang: 'Rượu mạnh và rượu trắng (Triệu lít)',
        samDungChoOtoMayBay: 'Săm dùng cho ô tô, máy bay (Nghìn cái)',
        samDungChoXeDapXeMay: 'Săm dùng cho xe đạp, xe máy (Nghìn cái)',
        satThepDangThoiDucHoacDangThoKhac:
            N'Sắt, thép dạng thỏi đúc hoặc dạng thô khác (Nghìn tấn)',
        soi: 'Sợi (Nghìn tấn)',
        soiDaCuoi: 'Sỏi, đá cuội (Nghìn m3)',
        suDanDung: 'Sứ dân dụng (Triệu cái)',
        suVeSinh: 'Sứ vệ sinh (Nghìn cái)',
        suaBot: 'Sữa bột (Nghìn tấn)',
        suaTamSuaRuaMat: 'Sữa tắm, sữa rửa mặt (Tấn)',
        suaTuoi: 'Sữa tươi (Triệu lít)',
        tamLopFiproXiMang: 'Tấm lợp fipro xi-măng (Triệu m2)',
        thanSach: 'Than sạch (Nghìn tấn)',
        thepCanVaThepHinh: 'Thép cán và thép hình (Nghìn tấn)',
        thitHop: 'Thịt hộp (Tấn)',
        thucAnChoGiaSucVaGiaCam: 'Thức ăn cho gia súc và gia cầm (Nghìn tấn)',
        thucAnChoThuySan: 'Thức ăn cho thủy sản (Nghìn tấn)',
        thuocDanhRang: 'Thuốc đánh răng (Tấn)',
        thuocDietCo: 'Thuốc diệt cỏ (Tấn)',
        thuocLa: 'Thuốc lá (Triệu bao)',
        thuocTruSau: 'Thuốc trừ sâu (Tấn)',
        thuySanDongHop: 'Thủy sản đóng hộp (Tấn)',
        thuySanUopDong: 'Thủy sản ướp đông (Nghìn tấn)',
        tiViLapRap: 'Ti vi lắp ráp (Nghìn cái)',
        tuLanhVaTuDongDungTrongGiaDinh:
            N'Tủ lạnh và tủ đông dùng trong gia đình (Nghìn cái)',
        vai: 'Vải (Triệum2)',
        xeDapCacLoai: 'Xe đạp các loại (Nghìn cái)',
        xeMoToXeMayLapRap: 'Xe mô tô, xe máy lắp ráp (Nghìn cái)',
        xiMang: 'Xi măng (Nghìn tấn)',
    `,
  })
  industry: string;
}