export const industries = [
  {
    vietnameseName: 'Hàng tiêu dùng cá nhân và gia đình',
    tickers: [],
    PerChange1D: 0,
    PerChange5D: 0,
    PerChange1M: 0,
    PerChange1Y: 0,
  },
  {
    vietnameseName: 'Hóa chất',
    tickers: [],
    PerChange1D: 0,
    PerChange5D: 0,
    PerChange1M: 0,
    PerChange1Y: 0,
  },
  {
    vietnameseName: 'Thực phẩm và đồ uống',
    tickers: [],
    PerChange1D: 0,
    PerChange5D: 0,
    PerChange1M: 0,
    PerChange1Y: 0,
  },
  {
    vietnameseName: 'Dịch vụ tài chính',
    tickers: [],
    PerChange1D: 0,
    PerChange5D: 0,
    PerChange1M: 0,
    PerChange1Y: 0,
  },
  {
    vietnameseName: 'Bán lẻ',
    tickers: [],
    PerChange1D: 0,
    PerChange5D: 0,
    PerChange1M: 0,
    PerChange1Y: 0,
  },
  {
    vietnameseName: 'Bất động sản',
    tickers: [],
    PerChange1D: 0,
    PerChange5D: 0,
    PerChange1M: 0,
    PerChange1Y: 0,
  },
  {
    vietnameseName: 'Ngân hàng',
    tickers: [],
    PerChange1D: 0,
    PerChange5D: 0,
    PerChange1M: 0,
    PerChange1Y: 0,
  },
  {
    vietnameseName: 'Viễn thông',
    tickers: [],
    PerChange1D: 0,
    PerChange5D: 0,
    PerChange1M: 0,
    PerChange1Y: 0,
  },
  {
    vietnameseName: 'Bảo hiểm',
    tickers: [],
    PerChange1D: 0,
    PerChange5D: 0,
    PerChange1M: 0,
    PerChange1Y: 0,
  },
  {
    vietnameseName: 'Xây dựng và vật liệu xây dựng',
    tickers: [],
    PerChange1D: 0,
    PerChange5D: 0,
    PerChange1M: 0,
    PerChange1Y: 0,
  },
  {
    vietnameseName: 'Tài nguyên cơ bản',
    tickers: [],
    PerChange1D: 0,
    PerChange5D: 0,
    PerChange1M: 0,
  },
  {
    vietnameseName: 'Các sản phẩm và dịch vụ công nghiệp',
    tickers: [],
    PerChange1D: 0,
    PerChange5D: 0,
    PerChange1M: 0,
    PerChange1Y: 0,
  },
  {
    vietnameseName: 'Truyền thông',
    tickers: [],
    PerChange1D: 0,
    PerChange5D: 0,
    PerChange1M: 0,
    PerChange1Y: 0,
  },
  {
    vietnameseName: 'Y tế',
    tickers: [],
    PerChange1D: 0,
    PerChange5D: 0,
    PerChange1M: 0,
    PerChange1Y: 0,
  },
  {
    vietnameseName: 'Các dịch vụ hạ tầng',
    tickers: [],
    PerChange1D: 0,
    PerChange5D: 0,
    PerChange1M: 0,
    PerChange1Y: 0,
  },
  {
    vietnameseName: 'Dầu khí',
    tickers: [],
    PerChange1D: 0,
    PerChange5D: 0,
    PerChange1M: 0,
    PerChange1Y: 0,
  },
  {
    vietnameseName: 'Công nghệ',
    tickers: [],
    PerChange1D: 0,
    PerChange5D: 0,
    PerChange1M: 0,
    PerChange1Y: 0,
  },
  {
    vietnameseName: 'Ôtô và linh kiện ôtô',
    tickers: [],
    PerChange1D: 0,
    PerChange5D: 0,
    PerChange1M: 0,
    PerChange1Y: 0,
  },
  {
    vietnameseName: 'Quỹ mở & Quỹ đóng ',
    tickers: [],
    PerChange1D: 0,
    PerChange5D: 0,
    PerChange1M: 0,
    PerChange1Y: 0,
  },
];
