export const industryMapping = {
  baoHiem: `N'%Bảo hiểm%'`,
  batDongSan: `N'%Bất động sản%'`,
  congNghe: `N'%Công nghệ%'`,
  dauKhi: `N'%Dầu khí%'`,
  banLe: `N'%Dịch vụ bán lẻ%'`,
  taiChinh: `N'%Dịch vụ tài chính%'`,
  tienIch: `N'%Dịch vụ tiện ích%'`,
  doGiaDung: `N'%Đồ dùng cá nhân và đồ gia dụng%'`,
  duLich: `N'%Du lịch & Giải trí%'`,
  hangHoa: `N'%Hàng hóa và dịch vụ công nghiệp%'`,
  hoaChat: `N'%Hóa chất%'`,
  nganHang: `N'%Ngân hàng%'`,
  oto: `N'%Ôtô & linh kiện phụ tùng%'`,
  truyenThong: `N'%Phương tiện truyền thông%'`,
  thucPham: `N'%Thực phẩm & Đồ uống%'`,
  vienThong: `N'%Viễn thông%'`,
  xayDung: `N'%Xây dựng & Vật liệu%'`,
  yTe: `N'%Y tế%'`,
};
